.TH CLODD 1 "MAY 2008" "version 1.0" "USER COMMANDS"

.SH NAME 

clodd \- copy host system files to and from the Clown disk image file

.SH SYNOPSIS
.B clodd 
[-h|--help] [-v]

.B clodd 
[-sector
.IR sec ] 
[-track
.IR tr ] 
[-count
.IR cnt ]
[-unpack]  [-q] -todisk
.I host-file

.B clodd 
[-sector
.IR sec ]
[-track
.IR tr ] 
[-count
.IR cnt ]
[-unpack] [-q] -fromdisk
.I host-file

.SH DESCRIPTION
.B clodd
is the Clown disk copy utility (named after the 
.SM UNIX 
.IR dd ). 
It is used to copy host system files to the Clown disk image file and
back.
.P
The default behavior of
.B clodd 
is to copy data verbatim, so that each host word is recorded as a
Clown word, and vice versa. If the 
.I \-unpack 
option is used, then 
.B clodd 
records each host byte as a Clown word, and each Clown word as a host
byte (the least significant byte of the Clown word is recorder, the
other three bytes are discarded). This option is useful when copying
text files: Clown has only one data type, and a printable character is
internally represented as a word.

.SH OPTIONS
.TP
\-h, \-\-help
Show the help message and exit
.TP 
\-sector sec 
Read from or write to sector
.I sec
(default 0)
.TP 
\-track tr 
Read from or write to track 
.I tr
(default 0)
.TP
\-count cnt
Read at most
.I cnt 
blocks (default: read the entire disk)
.TP
\-unpack
Record each 8-bit character as one Clown word while writing to the
disk, or record each Clown word as an 8-bit character while reading
from the disk
.TP
\-fromdisk
Copy from the the disk image to the
.I host-file
.TP
\-todisk
Copy from the 
.I host-file
to the disk image
.TP 
\-q, \-\-silent 
Operate silently, without reporting warnings and error messages
.TP 
\-v
Print the  version number and exit

.SH FILES
The disk image is assumed to be in the file 
.IR clown.dsk .

.SH ENVIRONMENT
.TP 
CLOWN_DISC
If set, the disk image file is searched in directory
.IR CLOWN_DISC .

.SH AUTHOR
Dmitry Zinoviev <dmitry at mcs dot suffolk dot edu>
.SH "SEE ALSO"
.BR clown (1),
.BR makedisc (1)
