include ../Makefile.conf

install:
	mkdir -p $(DESTDIR)/man/man1
	install -m 644 clink.1 $(DESTDIR)/man/man1/clown.1
	install -m 644 clink.1 $(DESTDIR)/man/man1/cas.1
	install -m 644 clink.1 $(DESTDIR)/man/man1/clink.1
	install -m 644 clink.1 $(DESTDIR)/man/man1/clodd.1
	install -m 644 clink.1 $(DESTDIR)/man/man1/makedisk.1

clean:
	rm -rf $(DESTDIR)/man/man1 *~