all:
	make -C codelib
	make -C devlib
	make -C cas
	make -C clink
	make -C clown
	make -C makedisc
	make -C clodd

clean:
	make -C codelib clean
	make -C devlib clean
	make -C cas clean
	make -C clink clean
	make -C clown clean
	make -C makedisc clean
	make -C clodd clean

cleanall:
	make -C codelib cleanall
	make -C devlib cleanall
	make -C cas cleanall
	make -C clink cleanall
	make -C clown cleanall
	make -C makedisc cleanall
	make -C clodd cleanall
